application: valery-yushchenko-site
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /rss/blog
  static_files: rss.xml
  upload: rss.xml


- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)

- url: /styles/(.*)
  static_files: styles/\1
  upload: styles/(.*)

- url: /scripts/(.*)
  static_files: scripts/\1
  upload: scripts/(.*)



- url: /.*
  script: main.py