application: valery-yushchenko-site
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt


- url: /images
  static_dir: images

- url: /styles/sandbox
  static_dir: styles/sandbox

- url: /styles
  static_dir: styles

- url: /scripts/sandbox
  static_dir: scripts/sandbox

- url: /scripts/libs
  static_dir: scripts/libs


- url: /.*
  script: main.py