application: valery-yushchenko-site
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: other/favicon.ico
  upload: other/favicon.ico

- url: /styles
  static_dir: styles

- url: /.*
  script: main.py