application: valery-yushchenko-site
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /rss/blog
  static_files: rss.xml
  upload: rss.xml


- url: /(images|styles|scripts|files)/(.*)
  static_files: \1/\2
  upload: (images|styles|scripts|files)/(.*)


- url: /.*
  script: main.py